server:
  port: 8089

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:8088/jobOffers
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
http:
  offer:
    scheduler:
      request:
       delay: PT10M

scheduling:
  enabled: true

offer:
  http:
    client:
      config:
         connectionTimeout: 1000
         port: 5057
         readTimeout: 1000
         uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com:9090/

